// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgkktjlkdbfhwgjzvpqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNna2t0amxrZGJmaHdnanp2cHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTU4MzUsImV4cCI6MjA2NTIzMTgzNX0.OHHOpiLjZIyK2ibzEMk7jW5DJA1Xs0yr4q1J322Q5-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);